# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/fleur/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),fleur)

$(call add-radio-file-sha1-checked,radio/audio_dsp.img,d9fd3fc5c94eed8a177b02d7c173cc900bbf3ac1)
$(call add-radio-file-sha1-checked,radio/gz.img,0193186a69fdff086fd781f5f4e8e1cecb70d46f)
$(call add-radio-file-sha1-checked,radio/lk.img,db6ca8023cc0a5a8575662a3a9a5360a2dbaf312)
$(call add-radio-file-sha1-checked,radio/logo.img,fd7fc9ed28e4d2e1784a2ebbdb468c4fdbf6dcb9)
$(call add-radio-file-sha1-checked,radio/md1img.img,92420599b9edf6663d2c1ed0b35ec51190b7b00d)
$(call add-radio-file-sha1-checked,radio/pi_img.img,ae5dd9192e13477a5a3e5e74d3367d1f9620c81c)
$(call add-radio-file-sha1-checked,radio/preloader_raw.img,389b8d44b8dad68248a1711767a882a30157b150)
$(call add-radio-file-sha1-checked,radio/scp.img,300eb758045a093cb6e7b2d7998a94558da45877)
$(call add-radio-file-sha1-checked,radio/spmfw.img,05f6b705105679c10fb0ca6c724584bd19682abe)
$(call add-radio-file-sha1-checked,radio/sspm.img,c6021e2544d9c68e3121d61c01bfaf877d0fca37)
$(call add-radio-file-sha1-checked,radio/tee.img,67c75e83b9b56de3ea7025781faa5d11dc5e2320)

endif
